"""
theory_validator.py — Post-Generation Theory File Validation
============================================================

Validates theory artifacts generated by the Theory Instructor to catch
common issues that would prevent files from working when a student opens
them.  This is a deterministic, non-LLM check that runs after generation.

Supported formats:
  - Format A (``.html``): HTML well-formedness, JavaScript syntax, common
    anti-patterns (missing null checks, scripts in <head>, no error handling).
  - Format B (``.sh``): Bash syntax check via ``bash -n``.
  - Format C (``.md``): Mermaid code block fence matching.

All checks are designed to be fast (< 100ms per file) and produce
actionable error messages that can be fed back to the agent or logged
for debugging.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class ValidationIssue:
    """A single issue found during validation."""

    severity: str  # "error" or "warning"
    message: str
    line: int | None = None
    snippet: str | None = None


@dataclass
class ValidationResult:
    """Result of validating a single theory file."""

    file_path: Path
    format_type: str  # "html", "shell", "markdown"
    passed: bool
    issues: list[ValidationIssue] = field(default_factory=list)

    @property
    def error_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == "error")

    @property
    def warning_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == "warning")


# ---------------------------------------------------------------------------
# HTML validation
# ---------------------------------------------------------------------------


class _ScriptExtractor(HTMLParser):
    """Extract inline <script> contents and their positions from HTML."""

    def __init__(self) -> None:
        super().__init__()
        self.scripts: list[dict] = []  # {content, start_line, in_head}
        self._current_tag: str | None = None
        self._current_start_line: int = 0
        self._in_head: bool = False
        self._script_depth: int = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "head":
            self._in_head = True
        elif tag == "script":
            self._current_tag = "script"
            self._current_start_line = self.getpos()[0]
            self._script_depth += 1
            # Check for src attribute (external scripts are fine)
            has_src = any(a[0] == "src" for a in attrs)
            if has_src:
                self._current_tag = None

    def handle_endtag(self, tag: str) -> None:
        if tag == "head":
            self._in_head = False
        elif tag == "script" and self._current_tag == "script":
            self._script_depth -= 1

    def handle_data(self, data: str) -> None:
        if self._current_tag == "script" and data.strip():
            self.scripts.append(
                {
                    "content": data,
                    "start_line": self._current_start_line,
                    "in_head": self._in_head,
                }
            )
        self._current_tag = None


def _validate_html(file_path: Path) -> ValidationResult:
    """Validate an HTML theory file.

    Checks:
      1. HTML is well-formed (parseable).
      2. No <script> tags in <head> (DOM elements won't exist yet).
      3. JavaScript syntax is valid (via Node.js --check).
      4. Common anti-patterns: missing try/catch, missing null checks on
         getElementById/querySelector.
      5. CSS anti-patterns: absolute positioning + negative margin (label
         overlap), dead BEM selectors, low-contrast text colours.
      6. ``keydown`` listeners that do not skip form controls.
    """
    result = ValidationResult(file_path=file_path, format_type="html", passed=True)

    try:
        raw_html = file_path.read_text(encoding="utf-8")
    except Exception as exc:
        result.passed = False
        result.issues.append(ValidationIssue("error", f"Cannot read file: {exc}"))
        return result

    # ── Check 1: HTML well-formedness ──────────────────────────────────
    try:
        extractor = _ScriptExtractor()
        extractor.feed(raw_html)
    except Exception as exc:
        result.passed = False
        result.issues.append(ValidationIssue("error", f"HTML parsing failed: {exc}"))
        return result

    # ── Check 2: Scripts in <head> ─────────────────────────────────────
    for script in extractor.scripts:
        if script["in_head"]:
            result.issues.append(
                ValidationIssue(
                    "error",
                    "<script> tag found inside <head> — DOM elements will not "
                    "exist when this script runs.  Move <script> to end of "
                    "<body> or wrap code in DOMContentLoaded listener.",
                    line=script["start_line"],
                )
            )
            result.passed = False

    # ── Check 3: JavaScript syntax ─────────────────────────────────────
    for i, script in enumerate(extractor.scripts):
        js_code = script["content"]
        try:
            proc = subprocess.run(
                ["node", "--check", "--input-type=module", "-"],
                input=js_code,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if proc.returncode != 0:
                stderr = proc.stderr.strip()
                # Extract line number from Node's error message if possible
                result.issues.append(
                    ValidationIssue(
                        "error",
                        f"JavaScript syntax error in script block {i + 1}: {stderr}",
                        line=script["start_line"],
                        snippet=(js_code[:200] + "..." if len(js_code) > 200 else js_code),
                    )
                )
                result.passed = False
        except FileNotFoundError:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    "Node.js not available — skipping JavaScript syntax check.",
                )
            )
        except subprocess.TimeoutExpired:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    f"JavaScript syntax check timed out for script block {i + 1}.",
                )
            )

    # ── Check 4: Common anti-patterns ──────────────────────────────────
    for i, script in enumerate(extractor.scripts):
        js_code = script["content"]

        # Check for getElementById/querySelector without null check
        # Pattern: const x = document.getElementById(...) or similar,
        # followed by usage without checking for null.
        dom_queries = re.findall(
            r"(?:const|let|var)\s+(\w+)\s*=\s*document\.(?:getElementById|querySelector)\([^)]+\)",
            js_code,
        )
        for var_name in dom_queries:
            # Treat the variable as checked if it appears in any guard:
            #   if (!x) ...   if (!x || !y) ...   if (x) ...
            #   if (x === null) ...   if (x !== null) ...
            null_check_pattern = re.compile(
                rf"(?:!\s*{re.escape(var_name)}\b"
                rf"|\b{re.escape(var_name)}\s*(?:===?|!==?)\s*null\b"
                rf"|if\s*\(\s*{re.escape(var_name)}\b)"
            )
            if not null_check_pattern.search(js_code):
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        f"DOM query result '{var_name}' is used without a null "
                        f"check.  If the element is missing, this will cause a "
                        f"runtime error.  Add: if (!{var_name}) {{ "
                        f"console.error('...'); return; }}",
                        line=script["start_line"],
                    )
                )

        # Check for missing try/catch around main initialization
        has_try_catch = bool(
            re.search(r"try\s*\{", js_code) and re.search(r"catch\s*\([^)]*\)\s*\{", js_code)
        )
        has_domcontentloaded = "DOMContentLoaded" in js_code

        if not has_try_catch and len(js_code) > 500:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    "No try/catch block found in script.  If initialization "
                    "fails, the student will see a blank page with no error "
                    "message.  Wrap the main render/init call in try/catch.",
                    line=script["start_line"],
                )
            )

        # Check for scripts that use DOM APIs but don't wait for DOMContentLoaded
        # (only if script is not at end of body — we already caught <head> scripts)
        uses_dom = bool(
            re.search(
                r"document\.(getElementById|querySelector|createElement|body)",
                js_code,
            )
        )
        if uses_dom and not has_domcontentloaded and not script["in_head"]:
            # Script is in <body> and uses DOM — make sure nothing but the
            # document's own closing tags follow it (i.e. it really is last).
            script_pos = raw_html.find(js_code)
            if script_pos >= 0:
                trailing = raw_html[script_pos + len(js_code):]
                trailing_clean = re.sub(
                    r"</script\s*>|</body\s*>|</html\s*>",
                    "",
                    trailing,
                    flags=re.IGNORECASE,
                ).strip()
                if trailing_clean:
                    result.issues.append(
                        ValidationIssue(
                            "warning",
                            "Script uses DOM APIs but may run before elements exist.  "
                            "Either place <script> as the LAST element in <body> or "
                            "wrap code in DOMContentLoaded listener.",
                            line=script["start_line"],
                        )
                    )

    # ── Check 5: CSS layout / selector anti-patterns ───────────────────
    style_blocks = re.findall(
        r"<style[^>]*>(.*?)</style>", raw_html, re.S | re.IGNORECASE
    )
    for block in style_blocks:
        for rule_match in re.finditer(r"([^{}]+)\{([^{}]*)\}", block):
            selector = rule_match.group(1).strip()
            rule_body = re.sub(r"\s+", "", rule_match.group(2)).lower()

            # (a) absolute positioning + negative left margin (classic overlap bug)
            if "position:absolute" in rule_body and re.search(
                r"margin-left:-\d", rule_body
            ):
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        f"CSS rule '{selector[:60]}' positions an element absolutely "
                        "and then shifts it with a negative 'margin-left' — this "
                        "commonly makes labels overlap their neighbours.  Prefer "
                        "'left: 50%' + 'transform: translateX(-50%)'.",
                    )
                )

            # (d) BEM modifier used as an element (missing leading '.')
            for tok in re.findall(r"(?<![.\w:-])([a-z0-9]+--[a-z0-9-]+)\b", selector):
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        f"Selector '{selector[:60]}' contains '{tok}', which looks "
                        "like a BEM modifier class written without a leading '.'.  "
                        "This selector will never match anything.",
                    )
                )

            # (c) low-contrast text colours on light backgrounds (skip dark
            # backgrounds and disabled controls, where contrast is exempt).
            has_dark_bg = re.search(r"background:#[0-2]", rule_body) is not None
            is_disabled = ":disabled" in selector.lower()
            if not has_dark_bg and not is_disabled:
                for colour_match in re.finditer(
                    r"color:\s*(#[0-9a-fA-F]{3,6})", rule_match.group(2)
                ):
                    hexval = colour_match.group(1).lower()
                    if hexval in ("#999", "#999999", "#777", "#777777"):
                        result.issues.append(
                            ValidationIssue(
                                "warning",
                                f"Low-contrast text colour '{hexval}' in rule "
                                f"'{selector[:60]}' fails WCAG AA for normal-sized "
                                "text.  Use a darker grey such as #555 or #6b7280.",
                            )
                        )

    # ── Check 6: keydown listener that does not skip form controls ─────
    for script in extractor.scripts:
        js_code = script["content"]
        if re.search(r"addEventListener\(\s*['\"]keydown['\"]", js_code):
            guarded = (
                "tagName" in js_code
                and re.search(r"SELECT|INPUT|TEXTAREA", js_code) is not None
            )
            if not guarded:
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        "A 'keydown' listener is registered but does not skip form "
                        "controls — arrow keys can hijack <select>/<input> elements.  "
                        "Ignore events where e.target.tagName is SELECT/INPUT/TEXTAREA.",
                        line=script["start_line"],
                    )
                )

    return result


# ---------------------------------------------------------------------------
# Shell script validation
# ---------------------------------------------------------------------------


def _validate_shell(file_path: Path) -> ValidationResult:
    """Validate a shell script theory file.

    Checks:
      1. Has shebang (#!/usr/bin/env bash or #!/bin/bash).
      2. Has 'set -euo pipefail' (or equivalent).
      3. Bash syntax is valid (bash -n).
    """
    result = ValidationResult(file_path=file_path, format_type="shell", passed=True)

    try:
        content = file_path.read_text(encoding="utf-8")
    except Exception as exc:
        result.passed = False
        result.issues.append(ValidationIssue("error", f"Cannot read file: {exc}"))
        return result

    # ── Check 1: Shebang ───────────────────────────────────────────────
    first_line = content.split("\n")[0].strip() if content else ""
    if not first_line.startswith("#!"):
        result.issues.append(
            ValidationIssue(
                "error",
                "Missing shebang.  Shell scripts must start with "
                "#!/usr/bin/env bash or #!/bin/bash.",
                line=1,
            )
        )
        result.passed = False
    elif "bash" not in first_line:
        result.issues.append(
            ValidationIssue(
                "warning",
                f"Shebang '{first_line}' does not reference bash.  Expected '#!/usr/bin/env bash'.",
                line=1,
            )
        )

    # ── Check 2: Safety settings ───────────────────────────────────────
    if "set -e" not in content and "set -o errexit" not in content:
        result.issues.append(
            ValidationIssue(
                "warning",
                "Missing 'set -e' (errexit).  Without this, the script "
                "will continue after errors, which can confuse students.",
            )
        )
    if "set -u" not in content and "set -o nounset" not in content:
        result.issues.append(
            ValidationIssue(
                "warning",
                "Missing 'set -u' (nounset).  Without this, typos in "
                "variable names become silent empty strings.",
            )
        )
    if "set -o pipefail" not in content:
        result.issues.append(
            ValidationIssue(
                "warning",
                "Missing 'set -o pipefail'.  Without this, errors in "
                "piped commands are silently ignored.",
            )
        )

    # ── Check 3: Bash syntax ───────────────────────────────────────────
    try:
        proc = subprocess.run(
            ["bash", "-n", str(file_path)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if proc.returncode != 0:
            stderr = proc.stderr.strip()
            result.issues.append(
                ValidationIssue(
                    "error",
                    f"Bash syntax error: {stderr}",
                )
            )
            result.passed = False
    except FileNotFoundError:
        result.issues.append(
            ValidationIssue(
                "warning",
                "bash not available — skipping shell syntax check.",
            )
        )
    except subprocess.TimeoutExpired:
        result.issues.append(
            ValidationIssue(
                "warning",
                "Bash syntax check timed out.",
            )
        )

    return result


# ---------------------------------------------------------------------------
# Markdown validation
# ---------------------------------------------------------------------------


def _validate_markdown(file_path: Path) -> ValidationResult:
    """Validate a Markdown theory file.

    Checks:
      1. Mermaid code blocks have matching opening/closing fences.
      2. At least one Mermaid diagram is present.
      3. Basic Markdown structure (has H1, has content).
    """
    result = ValidationResult(file_path=file_path, format_type="markdown", passed=True)

    try:
        content = file_path.read_text(encoding="utf-8")
    except Exception as exc:
        result.passed = False
        result.issues.append(ValidationIssue("error", f"Cannot read file: {exc}"))
        return result

    lines = content.split("\n")

    # ── Check 1: Mermaid fence matching ────────────────────────────────
    in_mermaid = False
    mermaid_start_line = 0
    mermaid_count = 0

    for i, line in enumerate(lines, start=1):
        stripped = line.strip()
        if stripped.startswith("```mermaid"):
            if in_mermaid:
                result.issues.append(
                    ValidationIssue(
                        "error",
                        f"Nested mermaid code block — missing closing ``` before line {i}.",
                        line=i,
                    )
                )
                result.passed = False
            in_mermaid = True
            mermaid_start_line = i
            mermaid_count += 1
        elif stripped == "```" and in_mermaid:
            in_mermaid = False
        elif stripped.startswith("```") and in_mermaid:
            # A different language fence inside mermaid — probably a mistake
            result.issues.append(
                ValidationIssue(
                    "error",
                    f"Found '{stripped}' inside mermaid block starting at "
                    f"line {mermaid_start_line}.  Did you forget to close "
                    f"the mermaid block with ```?",
                    line=i,
                )
            )
            result.passed = False

    if in_mermaid:
        result.issues.append(
            ValidationIssue(
                "error",
                f"Unclosed mermaid code block starting at line "
                f"{mermaid_start_line}.  Add ``` on its own line to close it.",
                line=mermaid_start_line,
            )
        )
        result.passed = False

    # ── Check 2: At least one Mermaid diagram ──────────────────────────
    if mermaid_count == 0:
        result.issues.append(
            ValidationIssue(
                "warning",
                "No Mermaid.js diagrams found.  Format C artifacts should "
                "include at least 2 mermaid code blocks.",
            )
        )

    # ── Check 3: Basic structure ───────────────────────────────────────
    has_h1 = any(line.strip().startswith("# ") for line in lines)
    if not has_h1:
        result.issues.append(
            ValidationIssue(
                "warning",
                "No H1 heading (# Title) found.  Every artifact should start with a clear title.",
            )
        )

    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def validate_theory_file(file_path: Path) -> ValidationResult:
    """Validate a single theory file based on its extension.

    Parameters
    ----------
    file_path : Path
        Path to the theory file to validate.

    Returns
    -------
    ValidationResult
        Result with pass/fail status and list of issues found.
    """
    suffix = file_path.suffix.lower()

    if suffix in (".html", ".htm"):
        return _validate_html(file_path)
    elif suffix == ".sh":
        return _validate_shell(file_path)
    elif suffix == ".md":
        return _validate_markdown(file_path)
    else:
        return ValidationResult(
            file_path=file_path,
            format_type="unknown",
            passed=True,
            issues=[
                ValidationIssue(
                    "warning",
                    f"Unknown file type '{suffix}' — no validation performed.",
                )
            ],
        )


def validate_theory_directory(theory_dir: Path) -> list[ValidationResult]:
    """Validate all theory files in a directory (non-recursive).

    Parameters
    ----------
    theory_dir : Path
        Directory containing theory files.

    Returns
    -------
    list[ValidationResult]
        One result per file found.  Empty list if directory doesn't exist.
    """
    if not theory_dir.exists() or not theory_dir.is_dir():
        return []

    results: list[ValidationResult] = []
    for file_path in sorted(theory_dir.iterdir()):
        if file_path.is_file() and not file_path.name.startswith("."):
            results.append(validate_theory_file(file_path))

    return results


def format_validation_report(results: list[ValidationResult]) -> str:
    """Format validation results as a human-readable Markdown report.

    Parameters
    ----------
    results : list[ValidationResult]
        Results from :func:`validate_theory_directory` or individual
        :func:`validate_theory_file` calls.

    Returns
    -------
    str
        Markdown-formatted report string.
    """
    if not results:
        return "*No theory files found to validate.*"

    total_errors = sum(r.error_count for r in results)
    total_warnings = sum(r.warning_count for r in results)
    total_files = len(results)
    passed_files = sum(1 for r in results if r.passed)

    lines: list[str] = [
        "## Theory File Validation Report",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Files checked | {total_files} |",
        f"| Files passed | {passed_files} |",
        f"| Files with errors | {total_files - passed_files} |",
        f"| Total errors | {total_errors} |",
        f"| Total warnings | {total_warnings} |",
        "",
    ]

    if total_errors == 0 and total_warnings == 0:
        lines.append("✅ **All theory files passed validation.**")
        return "\n".join(lines)

    for result in results:
        status = "✅" if result.passed else "❌"
        lines.append(f"### {status} `{result.file_path.name}` ({result.format_type})")
        lines.append("")

        if not result.issues:
            lines.append("*No issues found.*")
            lines.append("")
            continue

        for issue in result.issues:
            icon = "🔴" if issue.severity == "error" else "🟡"
            location = f" (line {issue.line})" if issue.line else ""
            lines.append(f"- {icon} **[{issue.severity.upper()}]{location}** {issue.message}")
            if issue.snippet:
                lines.append(f"  ```js\n  {issue.snippet}\n  ```")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # Test with the broken file from the user's report
    test_file = Path(
        "output/2026-08-23_204628_Javascript_OOP/labs/tier1_foundations/theory/"
        "prototype_and_class_visualizer.html"
    )

    if test_file.exists():
        print(f"Validating: {test_file}")
        result = validate_theory_file(test_file)
        print(f"  Passed: {result.passed}")
        print(f"  Errors: {result.error_count}")
        print(f"  Warnings: {result.warning_count}")
        for issue in result.issues:
            icon = "🔴" if issue.severity == "error" else "🟡"
            print(f"  {icon} {issue.message}")
    else:
        print(f"Test file not found: {test_file}")
        print("Run this after generating theory files to see validation in action.")
