"""
syllabus_review.py — Syllabus Feasibility Audit Task (Blueprint QA)
===================================================================

Issue #X: Blueprint QA Loop — Syllabus Feasibility Auditor

Defines a CrewAI **Task** that, when executed by the Education Director
agent, performs a rigorous feasibility audit of the generated syllabus
before the rest of the pipeline executes.  The task mandates:

  1. **Time-Budget Math** — Calculate exact minutes for every activity
     and verify they fit within the stated contact hours.
  2. **Workload Realism** — Assess whether the weekly workload is
     sustainable for MBO4 vocational students.
  3. **Scheduling Sanity** — Detect contradictory scheduling (e.g.,
     exams and projects in the same session).
  4. **MBO4 Appropriateness** — Verify content is pitched at the right
     level for 16-20 year-old vocational students.

If the syllabus contains impossible math or pedagogical flaws, the
Education Director is explicitly instructed to use CrewAI's delegation
mechanism to send the syllabus back to the Curriculum Architect for
targeted rewrites.
"""

from __future__ import annotations

from crewai import Agent, Task


def create_syllabus_review_task(
    *,
    agent: Agent,
    course_name: str,
    syllabus_context: str,
    material_language: str = "Dutch",
    human_feedback: str | None = None,
    verbose: bool = False,
) -> Task:
    """Create a CrewAI Task that performs a feasibility audit of a syllabus.

    Parameters
    ----------
    agent : Agent
        The Education Director agent that will execute this task.
    course_name : str
        The name of the vocational course (e.g. "Full-Stack Web Development").
    syllabus_context : str
        The full Markdown syllabus text generated by the Curriculum Architect.
    verbose : bool
        Enable detailed task execution logging.

    Returns
    -------
    Task
        Fully-configured CrewAI Task ready to be assigned to a Crew.
    """
    # ── Build the description ──────────────────────────────────────────
    description = (
        f"**🌐 LANGUAGE: ALL output (audit report, findings, recommendations) MUST "
        f"be written in {material_language}.**\n\n"
        f"## Feasibility Audit — Syllabus for: {course_name}\n\n"
        f"---\n\n"
        f"### Your Task\n\n"
        f"You have received a complete course syllabus generated by the "
        f"Curriculum Architect.  Your job is to perform a rigorous "
        f"**Feasibility Audit** before this syllabus is handed off to "
        f"the Theory Instructor and Lab Developer.  You are the gatekeeper.\n\n"
        f"Read the syllabus below carefully and perform the following "
        f"four checks:\n\n"
        f"---\n\n"
        f"### 🔍  Check 1: Time-Budget Mathematics\n\n"
        f"For EVERY module/session in the syllabus:\n\n"
        f"- Identify the **stated session duration** (e.g., '120 minutes', "
        f"'2 hours', '1 class period').\n"
        f"- List every activity described for that session (lecture, "
        f"lab exercise, exam, quiz, peer review, group discussion, "
        f"presentation, self-study assignment, etc.).\n"
        f"- Assign a **realistic minimum time** to each activity based on "
        f"your experience with MBO4 students.  Be conservative — students "
        f"need time for setup, transitions, questions, and cleanup.\n"
        f"- **Sum the activity times** and compare against the stated "
        f"session duration.\n"
        f"- If the total exceeds the available time, flag it as a "
        f"**TIME-BUDGET VIOLATION** with the exact deficit.\n\n"
        f"Example violations:\n"
        f"- 'A 90-minute exam + a 30-minute peer review + a 15-minute "
        f"lecture = 135 minutes in a 120-minute class → 15-minute deficit.'\n"
        f"- 'Module 4 lists 6 lab exercises at ~25 minutes each = 150 "
        f"minutes of lab work in a 90-minute session → 60-minute deficit.'\n\n"
        f"### 🔍  Check 2: Workload Realism\n\n"
        f"For each week of the course:\n\n"
        f"- Calculate the **total weekly hours** (contact hours + assigned "
        f"self-study/homework).\n"
        f"- MBO4 students should not exceed **40 total hours per week** "
        f"(contact + self-study combined).\n"
        f"- Flag any week that exceeds this threshold.\n"
        f"- Assess whether the self-study expectations are realistic for "
        f"students aged 16-20 who may have part-time jobs, family "
        f"responsibilities, or varying levels of prior knowledge.\n"
        f"- Flag any week that assumes university-level independence "
        f"(e.g., 'read chapters 5-8 and implement a REST API before next "
        f"class' with only 2 hours of self-study allocated).\n\n"
        f"### 🔍  Check 3: Scheduling Sanity\n\n"
        f"Review the week-by-week schedule for contradictions:\n\n"
        f"- **No exam + major project deadline in the same session.**\n"
        f"- **No more than one heavy assessment per week** (a 'heavy "
        f"assessment' is an exam, a major project submission, or a "
        f"graded presentation).\n"
        f"- **Prerequisites must come before dependents** — if Module 5 "
        f"requires knowledge of Docker, Docker must be introduced before "
        f"Module 5, not after.\n"
        f"- **Adequate spacing between assessments** — at least one "
        f"full week between a major project deadline and an exam.\n"
        f"- Flag any scheduling contradiction with a clear explanation "
        f"of why it is problematic for MBO4 students.\n\n"
        f"### 🔍  Check 4: MBO4 Appropriateness\n\n"
        f"Review the content for appropriate difficulty level:\n\n"
        f"- **No overly abstract patterns introduced too early** — design "
        f"patterns, architectural concepts, and theoretical frameworks "
        f"should be introduced gradually with concrete examples first.\n"
        f"- **No graduate-level content without scaffolding** — if advanced "
        f"topics appear (e.g., monads, category theory, formal verification), "
        f"they must be preceded by substantial foundational work.\n"
        f"- **Sufficient hands-on practice before assessments** — every "
        f"assessed topic must have at least one hands-on lab or exercise "
        f"before the assessment.\n"
        f"- **Language and instructions must be accessible** — instructions "
        f"should use concrete, everyday language.  Abstract jargon without "
        f"examples is a red flag.\n"
        f"- Flag any content that is inappropriate for MBO4 level with a "
        f"specific suggestion for how to adjust it.\n\n"
        f"---\n\n"
        f"### 🔴  CRITICAL: Delegation Mandate\n\n"
        f"If the syllabus contains **impossible time-budget math** (e.g., "
        f"a 90-minute exam and a peer review in a 120-minute class), "
        f"**unsustainable workloads**, **contradictory scheduling**, or "
        f"**MBO4-inappropriate content**, you **MUST** use CrewAI's "
        f"delegation mechanism to send it back to the **Curriculum "
        f"Architect** to rewrite that specific section.\n\n"
        f"Your delegation message must include:\n"
        f"1. **Which specific module(s) or section(s)** need to be "
        f"rewritten.\n"
        f"2. **What exactly is wrong** — quote the problematic text and "
        f"show your time calculations.\n"
        f"3. **Why it matters** for MBO4 students — explain the impact "
        f"on learning and student well-being.\n"
        f"4. **How to fix it** — provide concrete, specific rewrite "
        f"instructions (e.g., 'Remove the peer review from Module 3 "
        f"Session 2 and move it to Module 4, or reduce the exam from "
        f"90 minutes to 60 minutes').\n\n"
        f"Do NOT attempt to rewrite the syllabus yourself.  Your role is "
        f"to *audit and delegate*, not to *design*.  The Curriculum "
        f"Architect is responsible for implementing fixes based on your "
        f"feedback.\n\n"
        f"---\n\n"
        f"### 📋  Syllabus to Audit\n\n"
        f"```markdown\n"
        f"{syllabus_context}\n"
        f"```\n\n"
        f"---\n\n"
        f"### 📋  Expected Output\n\n"
        f"Produce a comprehensive **Markdown Feasibility Audit Report** "
        f"with the following sections:\n\n"
        f"```markdown\n"
        f"# Feasibility Audit Report — {course_name}\n\n"
        f"## Executive Summary\n"
        f"- Total modules audited: [count]\n"
        f"- Time-budget violations found: [count]\n"
        f"- Workload issues found: [count]\n"
        f"- Scheduling contradictions found: [count]\n"
        f"- MBO4 appropriateness issues found: [count]\n"
        f"- Delegation(s) sent to Curriculum Architect: [yes/no]\n"
        f"- **Overall Verdict: [APPROVED / NEEDS REVISION]**\n\n"
        f"## Check 1: Time-Budget Mathematics\n"
        f"[For each module: detailed time calculation, PASSED or FAILED "
        f"with specific deficit]\n\n"
        f"## Check 2: Workload Realism\n"
        f"[Week-by-week workload analysis, PASSED or FAILED with specific "
        f"issues]\n\n"
        f"## Check 3: Scheduling Sanity\n"
        f"[Schedule review, PASSED or FAILED with specific contradictions]\n\n"
        f"## Check 4: MBO4 Appropriateness\n"
        f"[Content-level review, PASSED or FAILED with specific concerns]\n\n"
        f"## Delegation Summary\n"
        f"[If fixes were delegated: exactly what was sent to the "
        f"Curriculum Architect, including the specific rewrite instructions]\n\n"
        f"## Sign-Off\n"
        f"[Final confirmation that the syllabus is feasible for MBO4 "
        f"students, or a clear statement that revisions are required "
        f"before the pipeline can continue]\n"
        f"```\n\n"
        f"If ALL checks pass for ALL modules, your sign-off must explicitly "
        f"state: '✅ **FEASIBILITY SIGN-OFF: This syllabus is "
        f"mathematically sound, workload-appropriate, and suitable for "
        f"MBO4 students.  Approved to proceed to Theory and Lab generation.**'\n"
    )

    # ── Inject human feedback (HITL loop) ───────────────────────────
    if human_feedback:
        description += (
            f"\n\n## ⚠️ Human Feedback (Instructor Review)\n\n"
            f"The following feedback was provided by a human reviewer "
            f"and MUST be addressed in this iteration:\n\n"
            f"{human_feedback}\n\n"
            f"Please revise the audit to incorporate this feedback "
            f"while maintaining all other requirements.\n"
        )

    expected_output = (
        "A comprehensive Markdown Feasibility Audit Report with "
        "Time-Budget Mathematics check results, Workload Realism "
        "analysis, Scheduling Sanity review, MBO4 Appropriateness "
        "assessment, a Delegation Summary (if any fixes were delegated "
        "to the Curriculum Architect), and a final Sign-Off confirming "
        "the syllabus is feasible for MBO4 students."
    )

    return Task(
        description=description,
        expected_output=expected_output,
        agent=agent,
        async_execution=False,
    )


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from src.agents.education_director import create_education_director

    agent = create_education_director(verbose=True)
    task = create_syllabus_review_task(
        agent=agent,
        course_name="Python for Data Engineering",
        syllabus_context="# Python for Data Engineering — Course Syllabus\n\n"
        "## Module 1: Introduction\n\n"
        "Duration: 120 minutes\n\n"
        "- Lecture: Course overview (30 min)\n"
        "- Lab: Python environment setup (45 min)\n"
        "- Quiz: Pre-assessment (15 min)\n"
        "- Peer review: Syllabus walkthrough (30 min)\n",
        verbose=True,
    )
    print("✅ Syllabus Review Task created successfully.\n")
    print(f"   Agent role:   {agent.role.split(chr(10))[0]}")
    print(f"   Async:        {task.async_execution}")
    print(f"   Description length: {len(task.description)} chars")
    print(f"   Expected output length: {len(task.expected_output)} chars")
